name = "glexer"
version = "2.0.0"
description = "A lexer for Gleam source code"
licenses = ["MIT"]
gleam = ">= 1.4.0"
repository = { type = "github", user = "DanielleMaywood", repo = "glexer" }

[dependencies]
gleam_stdlib = ">= 0.43.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.1"
