name = "glexer"
version = "2.3.0"
description = "A lexer for Gleam source code"
licenses = ["MIT"]
gleam = ">= 1.4.0"
repository = { type = "github", user = "DanielleMaywood", repo = "glexer" }

[javascript.deno]
allow_read = true

[dependencies]
gleam_stdlib = ">= 0.43.0 and < 1.0.0"
splitter = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.1"
simplifile = ">= 1.0.0 and < 3.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
